version: '3.6'

services:
  	db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: easytoguess
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: eveneasier

	wordpress:
    	depends_on:
       		- db
     	image: wordpress:latest
     	restart: always
     	volumes:
       		- ./wordpress:/var/www/html/wp-content
     	environment:
       		WORDPRESS_DB_HOST: db:3306
       		WORDPRESS_DB_USER: wordpress
       		WORDPRESS_DB_PASSWORD: eveneasier
       		WORDPRESS_DB_NAME: wordpress
       		VIRTUAL_HOST: thietbithongminh.pro
       		VIRTUAL_PORT: 80
       		LETSENCRYPT_HOST: thietbithongminh.pro 
	   		LETSENCRYPT_EMAIL: cuongtv.ee@gmai.com
	expose:
      	- 80
networks:
  	default:
    	external:
      		name: nginx-proxy
